import { Inter } from "next/font/google";
import "./globals.css";
 
import Link from "next/link"
import Home from "./page";
import NavBar from "./navbar/page";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
         <NavBar></NavBar>
         
        
        {children}

         <footer className="bg-gray-800 text-white p-4 text-center">
        © 2024 My Website
      </footer>
      </body>
    </html>
  );
}
