import { Inter } from "next/font/google";
import "./globals.css";  
import NavBar from "./navbar/page";  

// Font setup using the Inter font
const inter = Inter({ subsets: ["latin"] });

// Metadata for the layout
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
     
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
   
        <NavBar />

      
        {children}

      
        <footer className="bg-gray-800 text-white p-4 text-center">
          © 2024 My Website
        </footer>
      </body>
    </html>
  );
}
